### ISSUE TITLE
Notifier service based on Google Cloud Messaging

### ISSUE THREAD

**Issue by brice-morin** [SINTEF/sensapp#17]
It would be good to have a notifier that could notifies Android devices based on the GCM protocol

http://developer.android.com/google/gcm/index.html

**Comment by fungiboletus** [comment]
Out of scope for SensApp 2.

**Comment by fungiboletus** [comment]
Yes, we need to develop a sensor / time-series server that does stuff. 12 years later, it still doesn't exist though the situation is better in terms of available database and tools.

I thought it would be funny to revive the SensApp project and repository. But it shares about 0 line of code with the old Scala codebase.
